on:
  push:
    branches: [main]

jobs:
  rpm-build:
    runs-on: ubuntu-24.04
    container:
      image: fedora:latest
    steps:
      - name: Fetching Github repository
        uses: actions/checkout@v4
      - name: Preparing building dependencies
        run: |
          dnf install -y wget rpm-build redhat-rpm-config rpmautospec
          dnf builddep -y ./atrust.spec
      - name: Building RPM package
        run: sh ./build.sh
      - name: Rename
        run: |
          output=$(find . -type f "aTrust-*.rpm")
          version=$(rpm -qp --queryformat '%{VERSION}' $output)
          rename="aTrust-${version}-x86_64.rpm"
          mv $output $rename
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            aTrust-*.rpm
            LICENSE
